version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
    command: poetry run uvicorn qalamos.main:app --reload --host 0.0.0.0 --port 8000
